ALTER TABLE MEMBER
    ADD COLUMN CREATE_DATE TIMESTAMP without time zone;

ALTER TABLE MEMBER
    ADD COLUMN UPDATE_DATE TIMESTAMP without time zone;

ALTER TABLE AUTHORITY
    ADD COLUMN CREATE_DATE TIMESTAMP without time zone;

ALTER TABLE AUTHORITY
    ADD COLUMN UPDATE_DATE TIMESTAMP without time zone;
