CREATE TABLE IF NOT EXISTS AUDIT_LOG
(
    ID          BIGSERIAL primary key,

    MEMBER_ID BIGINT not null,
    MEMBER_TITLE VARCHAR(255) not null,
    CREATE_DATE TIMESTAMP without time zone,
    REQUEST_URL VARCHAR(255),
    ACTION_METHOD VARCHAR(50),
    ACTION_OBJECT_TYPE VARCHAR(255),
    ACTION_OBJECT_ID VARCHAR(255),
    RESPONSE_STATUS_CODE VARCHAR(255),
    RESPONSE_BODY TEXT
);
